title: Skylar MacDonald
tagline: Comedian
description: >-
  Silly joke teller. PowerPoint raconteur. Pretends to be people.
url: "https://skylarmacdonald.com"

theme: minima
plugins:
  - jekyll-feed
exclude:
  - .ruby-version
collections:
  projects:
    output: true
permalink: pretty
header_pages:
  - live.md
  - blog.md
  - contact.md

twitter_username: &twt helloiamskylar
instagram_username: helloiamskylar
facebook_username: &fb helloiamskylar

twitter:
  username: *twt
facebook:
  publisher: *fb

lang: en_GB
locale: en_GB
