title: Skylar MacDonald
tagline: Comedian
description: >-
  Silly joke teller. PowerPoint raconteur. Pretends to be people.
url: "https://skylarmacdonald.com"

theme: minima
plugins:
  - jekyll-feed
exclude:
  - .ruby-version
collections:
  projects:
    output: true
permalink: pretty
header_pages:
  - live.md
  - blog.md
  - contact.md

instagram_username: helloiamskylar
mastodon:
  - username: skylar
    instance: mastodon.social

facebook:
  publisher: helloiamskylar

lang: en_GB
locale: en_GB
